inicio/urls.py
from django.urls import path
from inicio import views
from .views import *


app_name = 'inicio'


urlpatterns = [
    path('', views.mi_vista, name='inicio'),
    path('crear-frase/', views.crear_frase, name='crear_frase'),
    path('editar-frase/<int:id>/', views.editar_frase, name='editar_frase'),
    path('editar-aviso/<int:id>/', views.editar_aviso, name='editar_aviso'),
    path('about/', views.about, name='about'),
    path('frases/', views.lista_frases, name='lista_frases'),
    path('crear-aviso/', views.crear_aviso, name='crear_aviso'),
    path('lista-avisos/', views.lista_avisos, name='lista_avisos'),
    path('eliminar/<int:id>/', Eliminar_frase_View.as_view(), name='eliminar_frase'),
    path('eliminar-aviso/<int:id>/', views.eliminar_aviso, name='eliminar_aviso'),
    path('ver_frase/<int:id>/', views.ver_frase, name='ver_frase'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('inicio/', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
] 
#if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/models.py
#from django.db import models
from django.db import models
from ckeditor.fields import RichTextField  


# Create your models here.


class Frase(models.Model):
    nombre = models.CharField(max_length=20)
    edad = models.IntegerField()
    frase = RichTextField()
    imagen = models.ImageField(upload_to='media/', null=True, blank=True)
    privado = models.BooleanField()

    def str(self):
        return f'Soy {self.nombre}, tengo {self.edad} y yo digo que {self.frase}'

class Aviso(models.Model):
    titulo = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=600)
 

    def str(self):
        return f'Soy {self.titulo} {self.descripcion}'

inicio/forms.py
from django import forms
from inicio.models import Frase, Aviso


class CrearFraseFormulario(forms.ModelForm):
    class Meta:
        model = Frase
        fields= ['nombre','imagen', 'edad', 'frase', 'privado']






class CrearAvisoFormulario(forms.ModelForm):
    class Meta:
        model = Aviso
        fields = ['titulo', 'descripcion']



class BuscarFrases(forms.Form):
    palabra = forms.CharField(max_length=20)

class BuscarUsuario(forms.Form):
    palabra = forms.CharField(max_length=20, required=False)

inicio/views.py
from django.http import HttpResponse, HttpResponseBadRequest
from django.template import Template, Context, loader, RequestContext
from inicio.models import Frase, Aviso
from usuarios.models import User
from datetime import datetime
from django.views import View

from django.shortcuts import render, redirect, get_object_or_404
from inicio.forms import CrearFraseFormulario, CrearAvisoFormulario, BuscarFrases
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin

class SuperuserRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser
def mi_vista(request):
    return render(request, 'inicio/index.html')

def about(request):
    return render(request, 'inicio/about.html')


def lista_frases(request):
    if not request.user.is_authenticated :
        lasfrases = Frase.objects.filter(privado__icontains=0 )
    else:
        lasfrases = Frase.objects.all()
    formulario_busqueda = BuscarFrases(request.GET)
    
    if formulario_busqueda.is_valid():
            palabra = formulario_busqueda.cleaned_data['palabra']
            lasfrases = lasfrases.filter(frase__icontains=palabra)
 
            


    return render(request, 'inicio/lista_frases.html', {'frases': lasfrases, 'formulario': formulario_busqueda})



def crear_frase(request):
    
    if request.method == "POST":
        formulario = CrearFraseFormulario(request.POST)
        
        if formulario.is_valid():
            datos_correctos = formulario.cleaned_data
        
            lafrase = Frase(nombre=datos_correctos['nombre'],imagen=datos_correctos['imagen'],edad=datos_correctos['edad'], frase=datos_correctos['frase'],privado=datos_correctos['privado'])
            lafrase.save()

            return render(request, 'inicio/ver_frase.html', {'mifrase': lafrase})
    
    formulario = CrearFraseFormulario()
    return render(request, 'inicio/crear_frase.html', {'formulario': formulario})


    

@user_passes_test(lambda u: u.is_superuser)

def editar_frase(request, id):
    frase = get_object_or_404(Frase,id=id)
    if request.method == 'POST':
        formulario = CrearFraseFormulario(request.POST, instance=frase)
        if formulario.is_valid():
            formulario.save()
            return redirect('inicio:lista_frases')
    else:
        
        formulario = CrearFraseFormulario(instance=frase)

    return render(request, 'inicio/editar_frase.html', { 'formulario': formulario, 'id':id})    

def editar_aviso(request, id):
    aviso = get_object_or_404(Aviso,id=id)
    if request.method == 'POST':
        formulario = CrearAvisoFormulario(request.POST, instance=aviso)
        if formulario.is_valid():
            formulario.save()
            return redirect('inicio:lista_avisos')
    else:
        
        formulario = CrearAvisoFormulario(instance=aviso)

    return render(request, 'inicio/editar_aviso.html', { 'formulario': formulario, 'id':id}) 


#@user_passes_test(lambda u: u.is_superuser)
class Eliminar_frase_View(SuperuserRequiredMixin, View):
    def eliminar_frase(request, id):
        frase = get_object_or_404(Frase, id=id)
        if request.method == 'POST':
            frase.delete()
            return redirect('inicio:lista_frases')
        return render(request, 'inicio/eliminar_frase.html', {'frase': frase})


def eliminar_aviso(request, id):
    aviso = get_object_or_404(Aviso, id=id)
    if request.method == 'POST':
        aviso.delete()
        return redirect('inicio:lista_avisos')
    return render(request, 'inicio/eliminar_aviso.html', {'aviso': aviso})



def crear_aviso(request):
    
    if request.method == "POST":
        formulario = CrearAvisoFormulario(request.POST)
        
        if formulario.is_valid():
            datos_correctos = formulario.cleaned_data
        
            elaviso = Aviso(titulo=datos_correctos['titulo'],descripcion=datos_correctos['descripcion'])
            elaviso.save()

            return redirect('inicio:crear_aviso')
    
    formulario = CrearAvisoFormulario()
    return render(request, 'inicio/crear_aviso.html', {'formulario': formulario})

def lista_avisos(request):
    
    avisos = Aviso.objects.all()
    formulario_busqueda= CrearAvisoFormulario()
 
            
    return render(request, 'inicio/lista_avisos.html', {'avisos': avisos, 'formulario': formulario_busqueda})

def ver_frase(request, id):
    mifrase = get_object_or_404(Frase, id=id)
    return render(request, 'inicio/ver_frase.html', {'mifrase': mifrase})
   #  mifrase = Frase.objects.filter(id__icontains=id )
   #  return render(request, 'inicio/ver_frase.html', {'mifrase': mifrase})

inicio/templates/inicio/about.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>about</title>
{% endblock title_head %}


{% block h1_header %}
<h1>About</h1>
{% endblock h1_header %}

{% block contenido %}
<div class="miformulario">
<br> Soy un profesional en el manejo de datos, con 3 años de
experiencia en el área. Estudio Ingeniería en Sistemas de
Información de la UTN y tengo vasta experiencia en Qliksense,
Qlikview, NPrinting, Data Model, ETLs, desarrollo, SQL, C#, .NET, C,
C++. También me apasiona la lectura, la música, el voley y el
ajedrez.<br> </div>
{% endblock contenido %}

inicio/templates/inicio/crear_aviso.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Centro de Avisos</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Quien es</h1>
{% endblock h1_header %}


{% block contenido %}
<form action={% url 'inicio:crear_aviso' %} method="POST">
    {% csrf_token %}
    <div class='miformulario'>
<li>
     {{formulario}} 
    </table>
    <button>Crear</button>
    </div>
</form>
{% endblock contenido %}

inicio/templates/inicio/crear_frase.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Crear Frase</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Su frase es</h1>
{% endblock h1_header %}


{% block contenido %}
<form action={% url 'inicio:crear_frase' %} method="POST">
    {% csrf_token %}
    <div class="miformulario">
<li>
     {{formulario}} 
    </table>
    <button class="botonredondo">Crear</button>
    </div>
</form>
{% endblock contenido %}

inicio/templates/inicio/crear_moderador.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Centro de Moderadores</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Quien es</h1>
{% endblock h1_header %}


{% block contenido %}
<form action={% url 'inicio:crear_moderador' %} method="POST">
    {% csrf_token %}
    <div class='formulario'>
<li>
     {{formulario}} 
    </table>
    <button>Crear</button>
    </div>
</form>
{% endblock contenido %}

inicio/templates/inicio/editar_aviso.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Editar aviso</title>
{% endblock title_head %}

{% block h1_header %}

<h1>Editar aviso</h1>

{% endblock h1_header %}

{% block contenido %}
<div class="miformulario">
<form method="POST">
    {% csrf_token %}
   
    {{ formulario.as_p}}

    <button class="botonredondo" type="submit">Guardar cambios</button>
</form>
</div>
{% endblock contenido %}

inicio/templates/inicio/editar_frase.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Editar frase</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Editar frase</h1>
{% endblock h1_header %}

{% block contenido %}
<div class="miformulario">
<form method="POST">
    {% csrf_token %}
    {{ formulario.as_p}}
    <button class="botonredondo" type="submit">Guardar cambios</button>
</form>
</div >
{% endblock contenido %}

inicio/templates/inicio/eliminar_aviso.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Eliminar aviso</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Editar aviso</h1>
{% endblock h1_header %}

{% block contenido %}



<form action={% url 'inicio:eliminar_aviso' aviso.pk %} method="POST">
    {% csrf_token %}
    <button class="botonredondo" type="submit">Eliminar</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/eliminar_frase.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Eliminar frase</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Editar frase</h1>
{% endblock h1_header %}

{% block contenido %}



<form action={% url 'inicio:eliminar_frase' frase.pk %} method="POST">
    {% csrf_token %}
    <button class="botonredondo" type="submit">Eliminar</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/index.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Frasemanía</h1>
{% endblock h1_header %}
<div class='formulario'>
</div >

inicio/templates/inicio/lista_avisos.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Frases</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Avisos</h1>





{% if request.user.is_superuser  %}
    <td>
        <form action={% url 'inicio:crear_aviso' %}   method="POST" >
            {% csrf_token %}
            <button class="botonredondo" type="submit">Crear Nuevo aviso</button>
        </form>
   
    </td>
    {% endif %}

    {% endblock h1_header %}
    {% block contenido %}
    <div class="miformulario">
{% if avisos %}
    {% for aviso in avisos %}
    <li>
         {{aviso.titulo}}
         {{aviso.descripcion}}
    

         {% if request.user.is_superuser  %}
         <td>
             <form action={% url 'inicio:editar_aviso' aviso.pk %} method="POST" style="display: inline;">
                 {% csrf_token %}
                 <button class="botonredondo" type="submit" >Editar</button>
             </form>
             <form  action={% url 'inicio:eliminar_aviso' aviso.pk %} method="POST" style="display: inline;">
                 {% csrf_token %}
                
                 <button class="botonredondo" type="submit">Eliminar</button>
                
             </form>
             {% endif %}
    </li>
    
    {% endfor %}

{% else %}
    <h2>Todo en orden.</h2>
{% endif %}
</div >
{% endblock contenido %}

inicio/templates/inicio/lista_frases.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Frases</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Listado de Frases</h1>




<p>
    <form action={% url 'inicio:lista_frases' %} >
        <div class='miformulario'>
            <li>
        {{formulario}}
        <button>Buscar</button>
        </div>
    </form>
</p>
{% endblock h1_header %}
{% block contenido %}
<div class='miformulario'>
{% if frases %}
    {% for mifrase in frases %}
    <li>
        Nombre: {{mifrase.nombre}} - Edad: {{mifrase.edad}}
        Frase : {{mifrase.frase}}
        <img src="{{ mifrase.imagen }}" alt="Imagen"></h2>
    </li>
    {% if request.user.is_superuser  %}
    <td>
        <form action={% url 'inicio:editar_frase' mifrase.pk %} method="POST" style="display: inline;">
            {% csrf_token %}
            <button class="botonredondo" type="submit">Editar</button>
        </form>
        <form action={% url 'inicio:eliminar_frase' mifrase.pk %} method="POST" style="display: inline;">
            {% csrf_token %}
            <button class="botonredondo" type="submit">Eliminar</button>
        </form>
   
    </td>
    {% endif %}
    {% endfor %}
</div>
{% else %}
    <h2>Hace tu primera frase!.</h2>
{% endif %}

{% endblock contenido %}

inicio/templates/inicio/lista_moderadores.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Frases</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Moderadores</h1>
{% endblock h1_header %}


{% block contenido %}


    <td>
        <form action={% url 'inicio:crear_moderador' %}   method="POST" >
            {% csrf_token %}
            <button type="submit">Crear Nuevo moderador</button>
        </form>
   
    </td>


{% if moderadores %}
    {% for moderador in moderadores %}
    <li>
         {{moderador.nombre}}
         {{moderador.apellido}}
    </li>
    
    {% endfor %}

{% else %}
    <h2>No hay moderadores por el momento.</h2>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/registro_exitoso.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>REGISTRO EXITOSO!</h1>
{% endblock h1_header %}

inicio/templates/inicio/ver_frase.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Mi Frase</title>
{% endblock title_head %}


{% block h1_header %}
<h1>Mi Frase</h1>
{% endblock h1_header %}

{% block contenido %}
<div class='miformulario'>
{% if mifrase.errors %}
<p>Formulario invalido</p>
{% endif %}

        <div>
            {{mifrase.frase}}
            {{mifrase.edad}}
            <img src={{ mifrase.imagen}} >
            {{mifrase.nombre}}


         

        </div>
       
 

 

</div>
{% endblock contenido %}