inicio/urls.py
from django.urls import path
from inicio import views
from .views import *


app_name = 'inicio'


urlpatterns = [
    path('', views.mi_vista, name='inicio'),
    path('crear-frase/', views.crear_frase, name='crear_frase'),
    path('editar-frase/<int:id>/', views.editar_frase, name='editar_frase'),
    path('editar-aviso/<int:id>/', views.editar_aviso, name='editar_aviso'),
    path('about/', views.about, name='about'),
    path('frases/', views.lista_frases, name='lista_frases'),
    path('crear-aviso/', views.crear_aviso, name='crear_aviso'),
    path('lista-avisos/', views.lista_avisos, name='lista_avisos'),
    path('eliminar/<int:id>/', Eliminar_frase_View.as_view(), name='eliminar_frase'),
    path('eliminar-aviso/<int:id>/', views.eliminar_aviso, name='eliminar_aviso'),
    path('ver_frase/<int:id>/', views.ver_frase, name='ver_frase'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('inicio/', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
] 
#if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings
from usuarios import views
from .views import *


app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registro/', views.registro, name='registro'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/cambiar_contrasenia', views.CambiarContrasenia.as_view(), name='cambiar_contrasenia'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('mi_perfil/<str:username>/', views.mi_perfil, name='mi_perfil'),
]

templates/genericos/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Template Base</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'inicio/css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'inicio:lista_frases' %}>Frases</a>
                
                
                <a class="navbar-brand" href={% url 'inicio:crear_frase' %}>Agregar frase</a>
                {% if request.user.is_authenticated %}
                <div class="user-info">
                    <a class="navbar-brand" href={% url 'usuarios:editar_perfil'  %}>Editar Perfil</a>
                    <a class="navbar-brand" href={% url 'usuarios:mi_perfil' username=request.user.username %}>Mi Perfil</a>
                    {% if request.user.infoextra.avatar %}
                    <img src="{{ request.user.infoextra.avatar.url }}" width="35" height="35">
                   
                    {% endif %}
                </div>


                
                <a class="navbar-brand" href={% url 'inicio:lista_avisos' %}>Avisos </a>
                
                <a class="btn btn-primary" href={% url 'usuarios:logout' %}>Logout</a>
                {% else %}
                <a class="btn btn-primary" href={% url 'usuarios:login' %}>Login</a>
                <a class="btn btn-primary" href={% url 'usuarios:registro' %}>Registrarse</a>
            </div>
            {% endif %}
        </nav>
        <!-- Masthead-->
        {% block header %}
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            {% block h1_header %}
                            <h1 class="mb-5">Bienvenidos Frasemania</h1>
                            {% endblock h1_header %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        {% if request.user.is_authenticated %}
                      
                        {% endif %}
                        <li class="nav-item">
                            <a class="list-inline-item" href={% url 'inicio:about' %}>About</a>
                        </li>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'inicio/js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>