inicio/urls.py
from django.urls import path
from inicio import views
from .views import *


app_name = 'inicio'


urlpatterns = [
    path('', views.mi_vista, name='inicio'),
    path('crear-frase/', views.crear_frase, name='crear_frase'),
    path('editar-frase/<int:id>/', views.editar_frase, name='editar_frase'),
    path('editar-aviso/<int:id>/', views.editar_aviso, name='editar_aviso'),
    path('about/', views.about, name='about'),
    path('frases/', views.lista_frases, name='lista_frases'),
    path('crear-aviso/', views.crear_aviso, name='crear_aviso'),
    path('lista-avisos/', views.lista_avisos, name='lista_avisos'),
    path('eliminar/<int:id>/', Eliminar_frase_View.as_view(), name='eliminar_frase'),
    path('eliminar-aviso/<int:id>/', views.eliminar_aviso, name='eliminar_aviso'),
    path('ver_frase/<int:id>/', views.ver_frase, name='ver_frase'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('inicio/', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
] 
#if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings
from usuarios import views
from .views import *


app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registro/', views.registro, name='registro'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/cambiar_contrasenia', views.CambiarContrasenia.as_view(), name='cambiar_contrasenia'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('mi_perfil/<str:username>/', views.mi_perfil, name='mi_perfil'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.

class InfoExtra(models.Model):
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    frase_descripcion = models.TextField(blank=True)
    avatar_thumbnail = models.ImageField(upload_to='avatares/', default='avatares/default_thumbnail.png')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.avatar:
            img = Image.open(self.avatar.path)
            output_size = (35, 35)
            img.thumbnail(output_size)
            img.save(self.avatar.path)
            img.save(self.avatar_thumbnail.path)

usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms
from usuarios.models import InfoExtra


class FormularioRegistro(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k: '' for k in fields}


class EdicionPerfil(UserChangeForm):
    password = None
    email = forms.EmailField()
    frase_descripcion=forms.CharField(label='frase_descripcion', max_length=30)
    first_name = forms.CharField(label='Nombre', max_length=30)
    last_name = forms.CharField(label='Apellido', max_length=30)

    avatar = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ['frase_descripcion','email', 'first_name', 'last_name', 'avatar']
        widgets = {
            'avatar': forms.ClearableFileInput(attrs={'multiple': False}),
        }
        labels = {
            'avatar': 'Imagen de perfil',
        }
        help_texts = {
            'avatar': 'Ingrese una imagen para su perfil (opcional)',
        }
        error_messages = {
            'avatar': {
                'invalid': "Formato de imagen no soportado. Solo se permiten los formatos JPG, PNG, y GIF.",
            }
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        try:
            info_extra = InfoExtra.objects.get(user=self.instance)
            self.fields['avatar'].initial = info_extra.avatar
        except InfoExtra.DoesNotExist:
            pass

    def save(self, commit=True):
        user = super().save(commit=commit)
        try:
            info_extra = InfoExtra.objects.get(user=user)
        except InfoExtra.DoesNotExist:
            info_extra = InfoExtra(user=user)
        if self.cleaned_data.get('avatar'):
            info_extra.avatar = self.cleaned_data.get('avatar')
        info_extra.save()
        return user

usuarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login as login_django
from usuarios.forms import FormularioRegistro, EdicionPerfil
from django.contrib.auth.decorators import login_required
from usuarios.models import InfoExtra
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View


def login(request):
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data.get('username')
            contrasenia = formulario.cleaned_data.get('password')
            user = authenticate(username=usuario, password=contrasenia)
            login_django(request, user)
            InfoExtra.objects.get_or_create(user=user)
            return redirect('inicio:inicio')
        else:
            return render(request, 'usuarios/login.html', {'form': formulario})
    formulario = AuthenticationForm()
    return render(request, 'usuarios/login.html', {'form': formulario})


def registro(request):
    if request.method == 'POST':
        formulario = FormularioRegistro(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('usuarios:login')
        else:
            return render(request, 'usuarios/registro.html', {'form': formulario})
    formulario = FormularioRegistro()
    return render(request, 'usuarios/registro.html', {'form': formulario})


@login_required
def editar_perfil(request):
    
    if request.method == 'POST':
        formulario = EdicionPerfil(request.POST, request.FILES, instance=request.user)
        
        if formulario.is_valid():
            formulario.save()
            infoextra = request.user.infoextra
            if 'avatar' in request.FILES:
                infoextra.avatar = request.FILES['avatar']
            infoextra.save()
            
            return redirect('usuarios:editar_perfil')
        else:
            return render(request, 'usuarios/editar_perfil.html', {'form': formulario})
        
    
    formulario = EdicionPerfil(instance=request.user)
    return render(request, 'usuarios/editar_perfil.html', {'form': formulario})

class CambiarContrasenia(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuarios/cambiar_contrasenia.html'
    success_url = reverse_lazy('usuarios:editar_perfil')
    

def mi_perfil(request, username):
    miperfil = get_object_or_404(InfoExtra, user__username=username)
    return render(request, 'usuarios/mi_perfil.html', {'miperfil': miperfil})

usuarios/templates/usuarios/cambiar_contrasenia.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Cambiar Contrasenia</title>
{% endblock title_head %}


{% block h1_header %}
<h1>Cambiar Contrasenia</h1>
{% endblock h1_header %}

{% block contenido %}

{% if form.error %}
<p>Formulario invalido</p>
{% endif %}

<form action={% url 'usuarios:cambiar_contrasenia' %} method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Cambiar</button>
</form>
{% endblock contenido %}

usuarios/templates/usuarios/editar_perfil.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Editar perfil</title>
{% endblock title_head %}


{% block h1_header %}
<h1>Editar perfil</h1>
{% endblock h1_header %}

{% block contenido %}
<div class='miformulario'>
{% if form.errors %}
<p>Formulario invalido</p>
{% endif %}

<form action="{% url 'usuarios:editar_perfil' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <table class="miformulario">
        
        {{ form.as_p }}
       
    </table>
    <button class='botonredondo' type="button"><a href="{% url 'usuarios:cambiar_contrasenia' %}">Cambiar Contraseña</a></button>
    <button class='botonredondo' type="submit">Editar</button>
</form>
</div>
{% endblock contenido %}

usuarios/templates/usuarios/login.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Login</title>
{% endblock title_head %}


{% block h1_header %}
<h1>Login</h1>
{% endblock h1_header %}

{% block contenido %}

{% if form.error %}
<p>Credenciales invalidas</p>
{% endif %}


<form action={% url 'usuarios:login' %} method="post">
    {% csrf_token %}

    <div class="miformulario">
        {{form.as_p}}
    </div>
    <button class="botonredondo">Loguearse</button>
</form>
{% endblock contenido %}

usuarios/templates/usuarios/logout.html
{% extends 'genericos/base.html' %}


{% block title_head %}
<title>Logout</title>
{% endblock title_head %}


{% block h1_header %}
<h1>Te deslogueaste con exito!!</h1>
{% endblock h1_header %}

{% block contenido %}
{% endblock contenido %}

usuarios/templates/usuarios/mi_perfil.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Editar perfil</title>
{% endblock title_head %}


{% block h1_header %}
<h1>Mi perfil</h1>
{% endblock h1_header %}

{% block contenido %}
<div class='miformulario'>
{% if miperfil.errors %}
<p>Formulario invalido</p>
{% endif %}

        <div>
            {% if request.user == perfil.user %}
            <a href="{% url 'usuarios:editar_descripcion' perfil.user.username %}" class="btn btn-primary">Editar Descripción</a>
            <a href="{% url 'usuarios:editar_enlace' perfil.user.username %}" class="btn btn-primary">Editar Enlace</a>
          {% endif %}
            <p>Nombre: {{ miperfil.user.first_name }} {{ miperfil.user.last_name }}</p>
            <p>Email: {{ miperfil.user.email }}</p>
            <p>Descripción: {{ miperfil.frase_descripcion }}</p>
            {% if request.user.infoextra.avatar %}
            <h2>Perfil de {{ miperfil.user.username }} <img src="{{ miperfil.avatar.url }}" alt="Foto de perfil"></h2>
            {% else %}
            <h2>Perfil de {{ miperfil.user.username }}</h2>
            {% endif %}


         

        </div>
       
 

 

</div>
{% endblock contenido %}

usuarios/templates/usuarios/registro.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Registrarse</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Registrarse</h1>
{% endblock h1_header %}

{% block contenido %}

{% if form.error %}
<p>Datos invalidos</p>
{% endif %}
<form action={% url 'usuarios:registro' %} method="post">
    {% csrf_token %}
    <div class="miformulario">
       
        {{form.as_p}}
  

    <button class="botonredondo">Registrarse</button>
</form>
</div>
{% endblock contenido %}